heat_template_version: 2016-10-14

description: |
  Deploy server to prime data volume for vdbench tests

parameters:
  image_id:
    type: string
    default: f8671a26-90ba-4ff7-9261-684cd155b023
  network_id:
    type: string
    default: bb3cfb5c-2310-4606-9124-4241be3637ec
  server_name:
    type: string
    default: vdbench_init_server
  key_name:
    type: string
    default: mykey
  vdbench_binary:
    type: string
    default: link
  user_data_format:
    type: string
    default:
  software_config_transport:
    type: string
    default:
  server_flavor:
    type: string
    default: m1.medium

resources:
  vdbench_install:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: config_scripts/setup_vdbench.yaml

  install_vdbench:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_install
      server: { get_resource: server }

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: server_flavor }
      networks:
        - network: { get_param: network_id }
      key_name: { get_param: key_name }
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG
      name: { get_param: server_name }
      security_groups: [ default ]

outputs:
  server_id:
    description: ID for server
    value: { get_resource: server }
