heat_template_version: 2016-10-14

description: |
  Deploy server to prime data volume for vdbench tests

parameters:
  image_id:
    type: string
    default: f8671a26-90ba-4ff7-9261-684cd155b023
  network_id:
    type: string
    default: bb3cfb5c-2310-4606-9124-4241be3637ec
  server_name:
    type: string
    default: vdbench_init_server
  key_name:
    type: string
    default: mykey

resources:
  vdbench_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: config_scripts/setup_vdbench.yaml

  vdbench_script:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: config_scripts/vdbench_data_device_setup.sh

  vdbench_run:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Run vdbench init script
          connection: local
          hosts: localhost
          tasks:
            - name: Set permissions on vdbench configuration
              file: path=/home/vdbench/vdbench_data_init.vdb owner=vdbench

            - name: Execute vdbench
              command: su - vdbench -c './vdbench -f vdbench_data_init.vdb'

  deploy_vdbench:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_config
      server: { get_resource: server }

  setup_vdbench_config:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_vdbench
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_script
      server:
        get_resource: server

  execute_vdbench:
    type: OS::Heat::SoftwareDeployment
    depends_on: setup_vdbench_config
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_run
      server: { get_resource: server }

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: m1.medium
      networks:
        - network: { get_param: network_id }
      key_name: { get_param: key_name }
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG
      name: { get_param: server_name }
      security_groups: [ default ]
      block_device_mapping:
        - volume_id: { get_resource: data_volume }
          device_name: vdb

  data_volume:
    type: OS::Cinder::Volume
    properties:
      description: Data volume for vdbench files
      name: vdbench_data_volume
      size: 10

