heat_template_version: 2016-10-14

description: |
  Deploy server to prime data volume for vdbench tests

parameters:
  image_id:
    type: string
    default: f8671a26-90ba-4ff7-9261-684cd155b023
  network_id:
    type: string
    default: bb3cfb5c-2310-4606-9124-4241be3637ec
  server_name:
    type: string
    default: vdbench_init_server
  key_name:
    type: string
    default: mykey
  vdbench_binary:
    type: string
    default: link

resources:
  vdbench_install:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: config_scripts/setup_vdbench.yaml

  vdbench_device:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config:
        get_file: config_scripts/mount_vdbench_data_fs.yaml

  install_vdbench:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_install
      server: { get_resource: server }

  vdbench_data_device:
    type: OS::Heat::SoftwareDeployment
    depends_on: install_vdbench
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_device
      server: { get_resource: server }

  server:
    type: host_w_vdbench.yaml
    properties:
      image: { get_param: image_id }
      flavor: m1.medium
      networks:
        - network: { get_param: network_id }
      key_name: { get_param: key_name }
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG
      name: { get_param: server_name }
      security_groups: [ default ]
      block_device_mapping:
        - volume_id: { get_resource: data_volume }
          device_name: vdb

  data_volume:
    type: OS::Cinder::Volume
    properties:
      description: Data volume for vdbench files
      name: vdbench_data_volume
      size: 10

outputs:
  data_volume_id:
    description: Cinder volume with initialized vdbench data
    value: { get_attr: [ data_volume, id ] }
