heat_template_version: 2016-10-14

description: |
  Deploy vdbench master server

parameters:
  image_id:
    description: Base boot image for vdbench server - should have Ansible hooks
    type: string
    default: f8671a26-90ba-4ff7-9261-684cd155b023
  network_id:
    description: Private network to host master server and minnions
    type: string
    default: bb3cfb5c-2310-4606-9124-4241be3637ec
  server_name:
    description: Server name for vdbench master server
    type: string
    default: vdbench_master_server
  key_name:
    description: Nova key for ssh login to vm
    type: string
    default: mykey
  vdbench_binary:
    description: Location of vdbench binary - should be http
    type: string
    default: link

resources:
  vdbench_init_script:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: config_scripts/vdbench_device_init.sh

  vdbench_run_init:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Run vdbench init script
          connection: local
          hosts: localhost
          tasks:
            - name: Set permissions on vdbench configuration
              file: path=/home/vdbench/vdbench_data_init.vdb owner=vdbench

            - name: Execute vdbench
              command: su - vdbench -c './vdbench -f vdbench_data_init.vdb'

  setup_vdbench_config:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_init_script
      server: { get_attr: [ server, server_id ] }

  execute_vdbench:
    type: OS::Heat::SoftwareDeployment
    depends_on: setup_vdbench_config
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: vdbench_run_init
      server: { get_attr: [ server, server_id ] }

  server:
    type: host_w_vdbench.yaml
    properties:
      image_id: { get_param: image_id }
      network_id: { get_param: network_id }
      key_name: { get_param: key_name }
      server_name: { get_param: server_name }
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG
